### ISSUE TITLE
Please oh please

### ISSUE THREAD

**Issue by nefaspartim** [Purvanshsingh/3commas#6]
Sir, please remove those keys from your test code if they are live. I came across this looking for py3cw examples and it could be dangerous for the wrong person to get their hands on those. Tried to message via LinkedIn, but of course I don't have premium so I couldn't reach you.

**Comment by Purvanshsingh** [comment]
@nefaspartim thanks for pointing it out, will remove it.
Thanks.

**Comment by nefaspartim** [comment]
You got it! Glad to help.

**Comment by Amantel** [comment]
Hey) I thought you will delete the repo after moving it to corporate github :)
Thanks @nefaspartim 

Oh, and Mongo creds are here too...
Sorry, @Purvanshsingh it's my fault for not doublechecking. 
Please delete the repo ASAP
